import * as yup from "yup";

export const ContactPageSchema = yup.object().shape({
  seo: yup.object({
    metaDesc: yup.mixed(),
    title: yup.mixed(),
    metaRobotsNofollow: yup.mixed(),
    metaRobotsNoindex: yup.mixed(),
  }),
  contactHeroSection: yup.object({
    bannertext_NL: yup.mixed(),
    bannertext_EN: yup.mixed(),
    bannertext_FR: yup.mixed(),
    bannertext_DE: yup.mixed(),
    bannertext_ES: yup.mixed(),
    bannerHeading: yup.array().of(
      yup.object({
        line_NL: yup.mixed(),
        line_EN: yup.mixed(),
        line_FR: yup.mixed(),
        line_DE: yup.mixed(),
        line_ES: yup.mixed(),
      })
    ),
    bannerBgImage: yup.object({
      node: yup.object({
        mediaItemUrl: yup.mixed(),
      }),
    }),
  }),
  contactSection: yup.object({
    contactSubHeading_NL: yup.mixed(),
    contactSubHeading_EN: yup.mixed(),
    contactSubHeading_FR: yup.mixed(),
    contactSubHeading_DE: yup.mixed(),
    contactSubHeading_ES: yup.mixed(),
    contactHeading_NL: yup.mixed(),
    contactHeading_EN: yup.mixed(),
    contactHeading_FR: yup.mixed(),
    contactHeading_DE: yup.mixed(),
    contactHeading_ES: yup.mixed(),
    detailsHeading_NL: yup.mixed(),
    detailsHeading_EN: yup.mixed(),
    detailsHeading_FR: yup.mixed(),
    detailsHeading_DE: yup.mixed(),
    detailsHeading_ES: yup.mixed(),
    address_NL: yup.mixed(),
    address_EN: yup.mixed(),
    address_FR: yup.mixed(),
    address_DE: yup.mixed(),
    address_ES: yup.mixed(),
    kvkNumberTitle_NL: yup.mixed(),
    kvkNumberTitle_EN: yup.mixed(),
    kvkNumberTitle_FR: yup.mixed(),
    kvkNumberTitle_DE: yup.mixed(),
    kvkNumberTitle_ES: yup.mixed(),
    kvkNumber: yup.mixed(),
    phoneNumber: yup.mixed(),
    email: yup.mixed(),
  }),
  contactUsFormSection: yup.object({
    contactFormTab_NL: yup.mixed(),
    contactFormTab_EN: yup.mixed(),
    contactFormTab_FR: yup.mixed(),
    contactFormTab_DE: yup.mixed(),
    contactFormTab_ES: yup.mixed(),
    contactnamelabel_NL: yup.mixed(),
    contactnamelabel_EN: yup.mixed(),
    contactnamelabel_FR: yup.mixed(),
    contactnamelabel_DE: yup.mixed(),
    contactnamelabel_ES: yup.mixed(),
    contactEmailLabel_NL: yup.mixed(),
    contactEmailLabel_EN: yup.mixed(),
    contactEmailLabel_FR: yup.mixed(),
    contactEmailLabel_DE: yup.mixed(),
    contactEmailLabel_ES: yup.mixed(),
    contactPhoneNumberLabel_NL: yup.mixed(),
    contactPhoneNumberLabel_EN: yup.mixed(),
    contactPhoneNumberLabel_FR: yup.mixed(),
    contactPhoneNumberLabel_DE: yup.mixed(),
    contactPhoneNumberLabel_ES: yup.mixed(),
    contactMessageLabel_NL: yup.mixed(),
    contactMessageLabel_EN: yup.mixed(),
    contactMessageLabel_FR: yup.mixed(),
    contactMessageLabel_DE: yup.mixed(),
    contactMessageLabel_ES: yup.mixed(),
    contactFormSendButton_NL: yup.mixed(),
    contactFormSendButton_EN: yup.mixed(),
    contactFormSendButton_FR: yup.mixed(),
    contactFormSendButton_DE: yup.mixed(),
    contactFormSendButton_ES: yup.mixed(),
  }),
  privacyPolicySection: yup.object({
    privacyPolicyPdf: yup.object({
      node: yup.object({
        mediaItemUrl: yup.mixed(),
      }),
    }),
    privacyPolicyUrlText_NL: yup.mixed(),
    privacyPolicyUrlText_EN: yup.mixed(),
    privacyPolicyUrlText_FR: yup.mixed(),
    privacyPolicyUrlText_DE: yup.mixed(),
    privacyPolicyUrlText_ES: yup.mixed(),
    privacyPolicyText_NL: yup.mixed(),
    privacyPolicyText_EN: yup.mixed(),
    privacyPolicyText_FR: yup.mixed(),
    privacyPolicyText_DE: yup.mixed(),
    privacyPolicyText_ES: yup.mixed(),
  }),
  sellingFormSection: yup.object({
    sellingTabTitle_NL: yup.mixed(),
    sellingTabTitle_EN: yup.mixed(),
    sellingTabTitle_FR: yup.mixed(),
    sellingTabTitle_DE: yup.mixed(),
    sellingTabTitle_ES: yup.mixed(),
    sellingNameLabel_NL: yup.mixed(),
    sellingNameLabel_EN: yup.mixed(),
    sellingNameLabel_FR: yup.mixed(),
    sellingNameLabel_DE: yup.mixed(),
    sellingNameLabel_ES: yup.mixed(),
    sellingEmailLabel_NL: yup.mixed(),
    sellingEmailLabel_EN: yup.mixed(),
    sellingEmailLabel_FR: yup.mixed(),
    sellingEmailLabel_DE: yup.mixed(),
    sellingEmailLabel_ES: yup.mixed(),
    sellingPhoneLabel_NL: yup.mixed(),
    sellingPhoneLabel_EN: yup.mixed(),
    sellingPhoneLabel_FR: yup.mixed(),
    sellingPhoneLabel_DE: yup.mixed(),
    sellingPhoneLabel_ES: yup.mixed(),
    sellingMessageLabel_NL: yup.mixed(),
    sellingMessageLabel_EN: yup.mixed(),
    sellingMessageLabel_FR: yup.mixed(),
    sellingMessageLabel_DE: yup.mixed(),
    sellingMessageLabel_ES: yup.mixed(),
    placeLabel_NL: yup.mixed(),
    placeLabel_EN: yup.mixed(),
    placeLabel_FR: yup.mixed(),
    placeLabel_DE: yup.mixed(),
    placeLabel_ES: yup.mixed(),
    licenseLabel_NL: yup.mixed(),
    licenseLabel_EN: yup.mixed(),
    licenseLabel_FR: yup.mixed(),
    licenseLabel_DE: yup.mixed(),
    licenseLabel_ES: yup.mixed(),
    imageLabel_NL: yup.mixed(),
    imageLabel_EN: yup.mixed(),
    imageLabel_FR: yup.mixed(),
    imageLabel_DE: yup.mixed(),
    imageLabel_ES: yup.mixed(),
    maxSizeLabel_NL: yup.mixed(),
    maxSizeLabel_EN: yup.mixed(),
    maxSizeLabel_FR: yup.mixed(),
    maxSizeLabel_DE: yup.mixed(),
    maxSizeLabel_ES: yup.mixed(),
    sellingButtonText_NL: yup.mixed(),
    sellingButtonText_EN: yup.mixed(),
    sellingButtonText_FR: yup.mixed(),
    sellingButtonText_DE: yup.mixed(),
    sellingButtonText_ES: yup.mixed(),
  }),
  articlesSection: yup.object({
    articleSubHeading_NL: yup.mixed(),
    articleSubHeading_EN: yup.mixed(),
    articleSubHeading_FR: yup.mixed(),
    articleSubHeading_DE: yup.mixed(),
    articleSubHeading_ES: yup.mixed(),
    articleHeading_NL: yup.mixed(),
    articleHeading_EN: yup.mixed(),
    articleHeading_FR: yup.mixed(),
    articleHeading_DE: yup.mixed(),
    articleHeading_ES: yup.mixed(),
    articles: yup.array().of(
      yup.object({
        title_NL: yup.mixed(),
        title_EN: yup.mixed(),
        title_FR: yup.mixed(),
        title_DE: yup.mixed(),
        title_ES: yup.mixed(),
        buttonText_NL: yup.mixed(),
        buttonText_EN: yup.mixed(),
        buttonText_FR: yup.mixed(),
        buttonText_DE: yup.mixed(),
        buttonText_ES: yup.mixed(),
        url: yup.mixed(),
      })
    ),
  }),
  contactSliderSection: yup.object({
    sliderTitle_NL: yup.mixed(),
    sliderTitle_EN: yup.mixed(),
    sliderTitle_FR: yup.mixed(),
    sliderTitle_DE: yup.mixed(),
    sliderTitle_ES: yup.mixed(),
    sliderText_NL: yup.mixed(),
    sliderText_EN: yup.mixed(),
    sliderText_FR: yup.mixed(),
    sliderText_DE: yup.mixed(),
    sliderText_ES: yup.mixed(),
    sliderItems: yup.array().of(
      yup.object({
        image: yup.object({
          node: yup.object({
            mediaItemUrl: yup.mixed(),
          }),
        }),
      })
    ),
  }),
});
